language: scala
scala:
  - 2.12.6
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
sudo: required
addons:
  chrome: stable
before_install:
  - mkdir webdriver
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip -o chromedriver_linux64.zip -d webdriver
  - export PATH=$PATH:$PWD/webdriver
script:
  - sbt test
  - sbt integrationTests/fastOptJS::webpack
  - cd integration-tests/gwen-workspace
  - ./gwen --parallel features